apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: furnishing
  project: furnishing
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.6.1
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true