apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: furnishing
  project: furnishing
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.13
    helm:
      parameters:
        - name: controller.ingressClassResource.name
          value: nginx
        - name: controller.ingressClassResource.default
          value: "true"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
    - group: v1
      kind: Service
      name: ingress-nginx-controller
      jsonPointers:
      - /spec/ipFamilies
      - /spec/ipFamilyPolicy
